#!/bin/sh /etc/rc.common

START=85

SPIN_SERVER_PID="/var/run/spind.pid"

spin_server_running() {
    if [ -e ${SPIN_SERVER_PID} ]; then
        ps w | grep ${SPIN_SERVER_PID} | grep spind 2>&1 > /dev/null
        [ $? == 0 ]
    else
        false
    fi
}

run_spin_server() {
    spind&
    echo $! > ${SPIN_SERVER_PID}
}

stop_spin_server() {
    if [ -e ${SPIN_SERVER_PID} ]; then
        kill `cat ${SPIN_SERVER_PID}`
        rm ${SPIN_SERVER_PID}
    fi
}

apply_spin_config() {
    cd /usr/lib/spin
    /usr/lib/spin/show_ips.lua -o /etc/spin/ignore.list
    spin_config ignore load /etc/spin/ignore.list
    spin_config block load /etc/spin/block.list
    spin_config except load /etc/spin/allow.list
}

start() {
    if spin_server_running; then
        echo "SPIN server already running"
    else
        echo "SPIN server not running"
        run_spin_server
    fi
}

stop() {
    stop_spin_server
}

restart() {
    stop
    start
}

reload() {
    stop
    start
}

enable() {
    ln -s /etc/init.d/spin /etc/rc.d/S${START}spin
    start
}

disable() {
    rm -f /etc/rc.d/S${START}spin
    stop
}
