#!/bin/sh /etc/rc.common

START=85
USE_PROCD=1
PROG=/usr/bin/spind
PIDFILE=/var/run/spind.pid

start_service() {
	procd_open_instance
	procd_set_param command $PROG
	procd_set_param pidfile $PIDFILE
	procd_close_instance
}
