#!/bin/sh
#
# Onboarding script for SHG

info() { logger -t shg-provisioning -p info $@; }
error() { logger -t shg-provisioning -p err $@; }
check_error() {
    if [ $? -ne 0 ]; then
        error $@
        exit 1
    fi
}

# TODO rename guest_turris, see also https://openwrt.org/docs/guide-user/network/wifi/guestwifi/guest-wlan if needed
uci set network.guest_turris=interface
uci set network.guest_turris.enabled='1'
uci set network.guest_turris.type='bridge'
uci set network.guest_turris.proto='static'
uci set network.guest_turris.ipaddr='10.111.222.1'
uci set network.guest_turris.netmask='255.255.255.0'
uci set network.guest_turris.bridge_empty='1'
uci set network.guest_turris.ip6assign='64'

uci set wireless.radio0=wifi-device
uci set wireless.radio0.type='mac80211'
uci set wireless.radio0.channel='auto'
#uci set wireless.radio0.hwmode='11a'
uci set wireless.radio0.hwmode='11g'
#uci set wireless.radio0.htmode='VHT80'
# Bring up the radio in 2.4ghz mode (HT20)
uci set wireless.radio0.htmode='HT20'
uci set wireless.radio0.disabled='0'
uci set wireless.radio0.country='CA'

# remove default Turris SSID
uci set wireless.default_radio0.disabled="1"

# now setup the guest wifi: SHG-onboard with WPA-onboard.
# make sure it has ULA assigned
uci set wireless.guest_iface_0=wifi-iface
uci set wireless.guest_iface_0.device='radio0'
# Let the device-manager enable this wifi access point...
#uci set wireless.guest_iface_0.disabled='0'
uci set wireless.guest_iface_0.disabled='1'
uci set wireless.guest_iface_0.mode='ap'
uci set wireless.guest_iface_0.ssid='SHG-onboard'
uci set wireless.guest_iface_0.network='guest_turris'
uci set wireless.guest_iface_0.encryption='psk2+ccmp'
uci set wireless.guest_iface_0.wpa_group_rekey='86400'
uci set wireless.guest_iface_0.key='SHG-onboard'
uci set wireless.guest_iface_0.ifname='guest_turris_0'
uci set wireless.guest_iface_0.isolate='1'


uci set dhcp.guest_turris=dhcp
uci set dhcp.guest_turris.interface='guest_turris'
uci set dhcp.guest_turris.ignore='0'
uci set dhcp.guest_turris.start='100'
uci set dhcp.guest_turris.limit='150'
uci set dhcp.guest_turris.leasetime='3600'
uci set dhcp.guest_turris.dhcp_option='6,10.111.222.1'
uci set dhcp.guest_turris.dhcpv6='server'
uci set dhcp.guest_turris.ra='server'

uci add firewall zone
uci add_list firewall.@zone[-1].network=guest_turris
uci set firewall.@zone[-1].name='guest_turris'
uci set firewall.@zone[-1].input='ACCEPT'
uci set firewall.@zone[-1].output='ACCEPT'
uci set firewall.@zone[-1].forward='REJECT'

uci add firewall rule
uci set firewall.@rule[-1].name=let-mgmt-https
uci set firewall.@rule[-1].target='ACCEPT'
uci set firewall.@rule[-1].proto='tcp'
uci set firewall.@rule[-1].dest_port='443'
uci set firewall.@rule[-1].src='guest_turris'
uci set firewall.@rule[-1].dest_ip="$(uci get network.lan.ipaddr)"

uci add firewall rule
uci set firewall.@rule[-1].name=let-mgmt-https6
uci set firewall.@rule[-1].target='ACCEPT'
uci set firewall.@rule[-1].proto='tcp'
uci set firewall.@rule[-1].dest_port='443'
uci set firewall.@rule[-1].family='ipv6'
uci set firewall.@rule[-1].src='guest_turris'

uci add firewall rule
uci set firewall.@rule[-1].name=let-onboard-https
uci set firewall.@rule[-1].target='ACCEPT'
uci set firewall.@rule[-1].proto='tcp'
uci set firewall.@rule[-1].dest_port='443'
uci set firewall.@rule[-1].proto='tcp'
uci set firewall.@rule[-1].family='ipv4'
uci set firewall.@rule[-1].src='guest_turris'
uci set firewall.@rule[-1].dest='wan'



# now setup the umdns to answer as we need.
uci add_list umdns.@umdns[0].network=guest_turris

# maybe this can be done by tweaking input to
#   /usr/share/mox/mox_autosetup

# socat - /tmp/kresd/control/2966
# > hints.set('nB73304.r.dasblinkenled.org 192.168.1.1')
# > hints.set('nB73304.r.dasblinkenled.org fdb7:3304:1cac::1')


# make uhttpd (LUCI) listen on another port as lighttpd will listen on 80 and 443
# TODO we should rather change lighttpd configuration
uci add_list uhttpd.main.listen_http='0.0.0.0:8080'
uci add_list uhttpd.main.listen_http='[::]:8080'
uci add_list uhttpd.main.listen_https='0.0.0.0:4443'
uci add_list uhttpd.main.listen_https='[::]:4443'

uci commit

# restart uhttpd (as we changed listening port)
/etc/init.d/uhttpd restart

