#!/bin/bash

if [ -z "$MY_RUBY_HOME" ]; then
    . /etc/profile.d/rvm.sh
    rvm use 2.6.1 >/dev/null
fi

export CERTDIR=/app/certificates
export SERVCERT=${CERTDIR}/jrc_prime256v1.crt
export SERVKEY=${CERTDIR}/jrc_prime256v1.key

RAILS_ENV=${RAILS_ENV-production}
export RAILS_ENV

cd /app/fountain
# Note: need to redirect output to file, otherwise app will shutdown after a while...
# Not sure why?!
bundle exec thin start --socket /root/mud-supervisor_skt --log /var/log/thin.log -D -V $@ &> /var/log/mud-supervisor.log

echo DONE
