#!/bin/bash

export LD_LIBRARY_PATH=/usr/local/rvm/rubies/ruby-2.6.3/lib/

if [ -z "$MY_RUBY_HOME" ]; then
    . /etc/profile.d/rvm.sh
    rvm use 2.6.3 >/dev/null
fi

export CERTDIR=/app/certificates
export SERVCERT=${CERTDIR}/jrc_prime256v1.crt
export SERVKEY=${CERTDIR}/jrc_prime256v1.key

RAILS_ENV=${RAILS_ENV-production}
export RAILS_ENV

cd /app/fountain

bundle exec rake db:migrate

# TEMP: These will be set-up during provisioning
if [ ! -f /root/setup ]; then
	bundle exec rake fountain:s0_set_hostname HOSTNAME=shg PORT=8081
	touch /root/setup
fi
if [ ! -f /app/certificates/ownerca_secp384r1.crt ]; then
    bundle exec rake fountain:s1_registrar_ca
fi
if [ ! -f /app/certificates/jrc_prime256v1.crt ]; then
    bundle exec rake fountain:s2_create_registrar
fi
# Does not work as openssl is not installed in LXC - Taken care in mud-supervisor's defaults file
if [ ! -f /app/certificates/jrc_prime256v1.key ]; then
    openssl ecparam -name secp384r1 -genkey -noout -out /app/certificates/jrc_prime256v1.key
fi

# clean up previous log entries in case they are owned by root
rm -f log/thin.log.1 tmp/pids/thin.pid
mv log/thin.log log/thin.log.1

# Note: need to redirect output to file, otherwise app will shutdown after a while...
# Not sure why?!
bundle exec thin start --ssl \
       --address ::    \
       --port    8081  \
       --user    fountain \
       --ssl-cert-file ${SERVCERT} \
       --ssl-key-file  ${SERVKEY} $@ &> /var/log/mud-supervisor.log

echo DONE
