#!/bin/sh

if [ -z "$(uci -q get uhttpd.shg)" ]; then
    LAN_IP=$(uci get network.lan.ipaddr)
    uci -q batch << EOI
set uhttpd.shg=uhttpd
add_list uhttpd.shg.listen_http='$LAN_IP:8080'
add_list uhttpd.shg.listen_https='$LAN_IP:8443'
set uhttpd.shg.redirect_https='0'
set uhttpd.shg.home='/srv/shg-device-manager'
set uhttpd.shg.rfc1918_filter='1'
set uhttpd.shg.max_requests='4'
set uhttpd.shg.max_connections='100'
set uhttpd.shg.cert='/etc/uhttpd.crt'
set uhttpd.shg.key='/etc/uhttpd.key'
set uhttpd.shg.cgi_prefix='/cgi-bin'
add_list uhttpd.shg.interpreter='.cgi=/usr/bin/p
set uhttpd.shg.script_timeout='60'
set uhttpd.shg.network_timeout='30'
set uhttpd.shg.http_keepalive='20'
set uhttpd.shg.tcp_keepalive='1'
commit uhttpd
EOI
    /etc/init.d/uhttpd reload
fi

exit 0
