#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=80
STOP=80
USE_PROCD=1

start_service() {
        lxc-start --name=mud-supervisor
        sleep 2
        lxc-attach --name=mud-supervisor  -- /root/start

        (cd /srv/lxc/mud-supervisor/rootfs/run && lua /usr/lib/lua/mud-supervisor/init.lua ) &
        chgrp 999  /srv/lxc/mud-supervisor/rootfs/run/mud_controller_skt
        chmod g+rw /srv/lxc/mud-supervisor/rootfs/run/mud_controller_skt
}

stop() {
        lxc-stop --name=mud-supervisor
}
